import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const indexHtml = await readFile(new URL("../public/index.html", import.meta.url), "utf-8");
const appJs = await readFile(new URL("../public/app.js", import.meta.url), "utf-8");
const pipelineJs = await readFile(new URL("../lib/pipeline.mjs", import.meta.url), "utf-8");
const principlesGuide = await readFile(new URL("../prompts/experiment_design_principles.md", import.meta.url), "utf-8");
const behaviorPrompt = await readFile(new URL("../prompts/behavior_task_breakdown_system.md", import.meta.url), "utf-8");
const experimentAlgorithm = await readFile(new URL("../../docs/experiment_algorithm.md", import.meta.url), "utf-8");

const textareaMatch = indexHtml.match(/<textarea[\s\S]*?data-input-content[\s\S]*?>([\s\S]*?)<\/textarea>/);
const rowsMatch = indexHtml.match(/<textarea[\s\S]*?data-input-content[\s\S]*?rows="(\d+)"/);
const stageSections = [...indexHtml.matchAll(/<section class="stage[^"]*" id="stage-[^"]+">[\s\S]*?<\/section>/g)]
  .map((match) => match[0]);

assert.ok(textareaMatch, "intake textarea should exist");
assert.equal(textareaMatch[1].trim(), "", "intake textarea should start empty");
assert.ok(rowsMatch, "intake textarea should define a compact row count");
assert.equal(Number(rowsMatch[1]) <= 7, true, "intake textarea should not dominate the landing page");
assert.equal(stageSections.some((section) => section.includes("section-head")), false, "workflow pages should not show explanatory headers under the main page title");
assert.equal(indexHtml.includes("告诉我们你想做什么实验"), false, "intake page should not show a redundant subtitle under the main title");
assert.equal(indexHtml.includes("请尽量详细地叙述你想做的实验"), false, "intake page should not show explanatory intro copy under the main title");
assert.ok(indexHtml.includes("按住录音"), "voice input should be press-and-hold recording");
assert.ok(indexHtml.includes("松开保存音频"), "voice input should store audio rather than claim transcription");
assert.ok(indexHtml.includes("上传并解析材料"), "upload materials entry should expose parsing");
assert.ok(indexHtml.includes("交给我们"), "submit should hand off to the system");
assert.equal(indexHtml.includes("自动转写"), false, "voice UI should not promise transcription yet");
assert.ok(indexHtml.includes("data-page=\"landing\""), "landing page should exist");
assert.ok(indexHtml.includes("data-page=\"auth\""), "login/register page should exist");
assert.ok(indexHtml.includes("从好奇心到快速可上手的 LLM 行为实验"), "landing headline should reflect the new positioning");
assert.equal(indexHtml.includes("从小组讨论到可运行的 LLM 行为实验"), false, "old landing headline should be removed");
assert.ok(indexHtml.includes("abstract-map"), "landing should use an abstract process visual");
assert.equal(indexHtml.includes("实验控制台"), false, "landing visual should not look like a console screenshot");
assert.equal(indexHtml.includes("class=\"mode-choice\""), false, "auth page should not ask users to choose personal/team mode");
assert.equal(indexHtml.includes("demo@llm-lab.local"), false, "auth and landing should not expose demo account details");
assert.ok(indexHtml.includes("stage-workspace"), "team workspace should exist");
assert.ok(indexHtml.includes("个人模式"), "personal workflow mode should be available");
assert.ok(indexHtml.includes("团队模式"), "team workflow mode should be available");
assert.ok(indexHtml.includes("data-mode-option=\"personal\""), "personal mode option should be wired");
assert.ok(indexHtml.includes("data-mode-option=\"team\""), "team mode option should be wired");
assert.ok(indexHtml.includes("data-team-only=\"true\""), "workspace step should be team-only");
assert.ok(indexHtml.includes("<span>01</span> 需求输入"), "workflow step 01 should be localized");
assert.ok(indexHtml.includes("<span>02</span> 细节确认"), "workflow step 02 should be detail confirmation");
assert.equal(indexHtml.includes("<span>02</span> 需求确认"), false, "workflow step 02 should not use the old demand confirmation label");
assert.ok(indexHtml.includes("<span>03</span> 实验协议"), "workflow step 03 should be protocol review");
assert.ok(indexHtml.includes("protocol-actions"), "protocol next-step button should live below the review content");
const protocolSectionHead = indexHtml.match(/<section class="stage" id="stage-protocol">[\s\S]*?<div class="two-col">/)?.[0] || "";
assert.equal(protocolSectionHead.includes("审查机器可运行的实验协议"), false, "protocol stage should not repeat a secondary explanatory heading");
assert.equal(protocolSectionHead.includes("先看人类可读摘要"), false, "protocol stage should not show redundant guidance before the panels");
assert.equal(protocolSectionHead.includes('data-action="confirm-protocol"'), false, "protocol next-step button should not sit in the top header");
assert.ok(indexHtml.includes("<h3>研究协议摘要</h3>"), "protocol stage should begin with the readable protocol summary");
assert.ok(indexHtml.includes("<h3>协议 JSON</h3>"), "protocol JSON should be visible as a regular panel heading");
assert.equal(indexHtml.includes("<summary>协议 JSON</summary>"), false, "protocol JSON should not be hidden behind a disclosure control");
assert.ok(indexHtml.includes("prompt-actions"), "prompt next-step button should live below the prompt review content");
const promptSectionHead = indexHtml.match(/<section class="stage" id="stage-prompt">[\s\S]*?<div class="two-col">/)?.[0] || "";
assert.equal(promptSectionHead.includes('data-action="confirm-prompt"'), false, "prompt next-step button should not sit in the top header");
const promptSection = indexHtml.match(/<section class="stage" id="stage-prompt">[\s\S]*?<\/section>/)?.[0] || "";
assert.ok(promptSection.includes('data-action="confirm-prompt"'), "prompt next-step button should remain available after the review content");
assert.ok(indexHtml.includes("<span>08</span> 结果报告"), "workflow step 08 should be localized");
assert.equal(indexHtml.includes("data-step-target=\"breakdown\""), false, "overview should not be a linear workflow step");
assert.ok(indexHtml.includes("global-overview"), "global overview card should live outside the workflow steps");
assert.ok(indexHtml.includes("确认并生成实验协议"), "copilot should send the user directly to protocol generation");
assert.ok(appJs.includes('setStep("protocol")'), "copilot compile should continue to protocol, not overview");
assert.equal(appJs.includes('setStep("breakdown")'), false, "overview should not be a blocking workflow destination");
assert.equal(indexHtml.includes("Research Intake"), false, "visible page title should not fall back to English");
assert.equal(indexHtml.includes("Task Breakdown"), false, "task breakdown label should not fall back to English");
assert.ok(indexHtml.includes("全局状态总览"), "global status overview copy should render");
assert.equal(indexHtml.includes("Report preview"), false, "report preview label should be localized");
assert.ok(indexHtml.includes("邀请成员"), "workspace should support inviting members");
assert.ok(indexHtml.includes("团队讨论"), "workspace should expose shared discussion");
assert.ok(indexHtml.includes("data-hypothesis-draft"), "previous copilot hypothesis draft field should be restored");
assert.ok(indexHtml.includes("假设问题拆解"), "detail confirmation should expose hypothesis breakdown");
assert.ok(indexHtml.includes("data-generation-status"), "detail confirmation should show whether the draft came from the LLM or fallback");
assert.ok(indexHtml.includes("生成的实验草案"), "detail confirmation should surface a structured generated experiment draft");
assert.ok(indexHtml.includes("data-plan-conditions"), "detail confirmation should render generated condition groups");
assert.ok(indexHtml.includes("data-plan-outcomes"), "detail confirmation should render generated outcomes");
assert.ok(appJs.includes("renderGenerationStatus"), "client should warn when the server falls back without an API key");
assert.ok(appJs.includes("renderGeneratedPlan"), "client should render the structured experiment draft");
assert.ok(indexHtml.includes("data-confirmation-details"), "detail confirmation should expose generated confirmation details");
assert.equal((indexHtml.match(/data-detail-field=/g) || []).length, 4, "detail confirmation should expose four lightweight experiment draft fields");
assert.ok(indexHtml.includes("条件分组"), "detail confirmation should focus on condition grouping");
assert.ok(indexHtml.includes("材料/提示词版本"), "detail confirmation should show material or prompt versions");
assert.ok(indexHtml.includes("因变量与评分方式"), "detail confirmation should show outcome and scoring choices");
assert.ok(indexHtml.includes("预实验计划与质量检查"), "detail confirmation should combine sampling and QA into one lightweight field");
assert.ok(indexHtml.includes("相关研究调研"), "detail confirmation should surface optional related research before finalizing");
assert.ok(indexHtml.includes("data-research-queries"), "related research module should expose suggested queries");
assert.ok(indexHtml.includes("data-research-results"), "related research module should render real retrieved results");
assert.ok(appJs.includes("research.results"), "client should read retrieved research results");
assert.ok(appJs.includes("research-result-card"), "client should render retrieved research cards");
assert.ok(appJs.includes("formatResearchEvidence"), "client should format research evidence ranking");
assert.ok(appJs.includes("research-evidence-badge"), "client should render evidence ranking badges");
assert.ok(appJs.includes('api("/api/research-search"'), "client should load literature search separately from intake");
assert.ok(appJs.includes("loadResearchResults"), "client should defer research loading after the draft appears");
assert.ok(appJs.includes("检索中"), "client should show an async research loading state");
assert.ok(indexHtml.includes("data-generation-note"), "detail confirmation should allow optional one-off generation guidance");
assert.ok(appJs.includes("generationNote"), "client should carry optional generation guidance into protocol generation");
assert.ok(appJs.includes("startGenerationTask"), "client should expose generation progress while API calls run");
assert.ok(appJs.includes("renderGenerationTray"), "client should render a lightweight generation task tray");
assert.ok(indexHtml.includes("data-task-tray"), "page should include the generation task tray mount");
assert.ok(experimentAlgorithm.includes("design transfer, not feature parity"), "algorithm contract should document design migration rather than feature cloning");
assert.ok(experimentAlgorithm.includes("End-To-End Contract"), "algorithm contract should define staged input/output contracts");
assert.ok(experimentAlgorithm.includes("Do not add course outlines"), "algorithm contract should explicitly reject CourseMaker feature parity");
assert.equal(indexHtml.includes("多智能体协作"), false, "internal agent workflow should not be exposed as page theory");
assert.equal(indexHtml.includes("内部由三个专职 agent"), false, "detail page should not explain the agent implementation");
assert.equal(indexHtml.includes("data-agent-workflow"), false, "internal agent workflow should not have a visible render target");
assert.equal(appJs.includes("renderAgentWorkflow"), false, "client should not render internal agent outputs");
assert.ok(pipelineJs.includes("buildAgentWorkflow"), "pipeline should still build internal agent outputs for task implementation");
assert.equal(indexHtml.includes("data-human-baseline"), false, "human baseline decision should be deferred to phase two");
assert.equal(indexHtml.includes("需要人类基线导出材料"), false, "human baseline option should not appear in copilot");
assert.equal(indexHtml.includes("导出人类基线"), false, "human baseline export should not appear in the results step");
assert.equal(indexHtml.includes("data-action=\"export-human\""), false, "human baseline export action should be removed from the visible UI");
assert.equal(indexHtml.includes("<h3>尚未确认</h3>"), false, "copilot should not show a separate unconfirmed section");
assert.equal(indexHtml.includes("确认我是否理解对了"), false, "detail confirmation should not repeat an explanatory section title");
assert.equal(indexHtml.includes("panel-hint"), false, "detail confirmation should not show redundant review guidance");
assert.equal(indexHtml.includes("copilot-understanding"), false, "detail confirmation should not show a separate understanding preface");
assert.ok(indexHtml.includes("<span>研究目标摘要</span>"), "detail confirmation should start with the editable study summary");
assert.ok(indexHtml.includes("data-benchmark-input"), "benchmark outcome should allow a benchmark name or link");
assert.ok(indexHtml.includes("<select data-models-input>"), "model list should be selected from a dropdown in model budget");
assert.equal(indexHtml.includes("inline-run-details"), false, "detail confirmation should not duplicate model or repetition settings");
assert.equal(indexHtml.includes("data-reps-input"), false, "detail confirmation should not include repetition controls");
assert.equal((indexHtml.match(/data-models-input/g) || []).length, 1, "model dropdown should only render once in model budget");
assert.equal(indexHtml.includes("<h3>研究细节确认</h3>"), false, "detail confirmation should not add a redundant panel heading");
assert.equal(indexHtml.includes("<h3>运行前要确定的细节</h3>"), false, "detail confirmation should not start with run settings");
assert.equal(indexHtml.includes("<h3>Copilot 摘要</h3>"), false, "copilot summary should not be the primary panel heading");
assert.equal(indexHtml.includes("Behavior prompts"), false, "copilot should not expose heavy behavior prompt checks");
assert.equal(indexHtml.includes("data-behavior-prompts"), false, "behavior prompts should stay out of the quick-pilot UI");
assert.equal(appJs.includes("behaviorPrompts"), false, "behavior prompts should not be rendered by the UI");
assert.ok(pipelineJs.includes("自由回答"), "free response measurement option should be generated");
assert.ok(pipelineJs.includes("打分 1-10"), "1-10 rating measurement option should be generated");
assert.ok(pipelineJs.includes("选择题"), "multiple-choice measurement option should be generated");
assert.ok(pipelineJs.includes("经典 benchmark 表现"), "benchmark measurement option should be generated");
assert.ok(principlesGuide.includes("operationalization"), "DOE-inspired operationalization guide should exist");
assert.ok(principlesGuide.includes("planned_comparisons"), "DOE-inspired planned comparison guide should exist");
assert.ok(behaviorPrompt.includes("Behavior Task Breakdown System Prompt"), "dedicated behavior task system prompt should exist");
assert.ok(behaviorPrompt.includes("拆解逻辑链"), "system prompt should define the general experiment breakdown chain");
assert.ok(behaviorPrompt.includes("最小可运行实验草案"), "system prompt should require a lightweight runnable draft before heavy methods fields");
assert.ok(behaviorPrompt.includes("快速文献调研触发"), "system prompt should cover optional quick literature research");
assert.ok(behaviorPrompt.includes("不要把模型名单当作实验条件"), "system prompt should prevent model names from becoming condition levels");
assert.ok(appJs.includes('api("/api/intake"'), "submit button should trigger the intake API that applies the behavior breakdown system prompt");
assert.ok(pipelineJs.includes("behavior_task_breakdown_v1"), "pipeline should mark the active breakdown logic chain");
assert.ok(pipelineJs.includes("内部实验设计原则"), "pipeline should inject the principle guide into the system prompt");
assert.equal(indexHtml.includes("deepseek + minimax 2.7"), false, "model dropdown should not include a mixed-model option");
assert.ok(indexHtml.includes("<option value=\"deepseek\" selected>deepseek</option>"), "deepseek should be the default single model");
assert.ok(indexHtml.includes("<option value=\"minimax 2.7\">minimax 2.7</option>"), "minimax should be available as a single model");
assert.ok(indexHtml.includes("重复试次"), "formal repetitions should use trial-count wording");
assert.equal(indexHtml.includes("status-pills"), false, "topbar should not show low-value status pills");
assert.equal(indexHtml.includes("data-status-intake"), false, "intake status chip should be removed");
assert.equal(indexHtml.includes("data-status-run"), false, "run status chip should be removed");
assert.equal(indexHtml.includes("intake empty"), false, "status copy should avoid internal jargon");
assert.equal(indexHtml.includes("no run"), false, "status copy should avoid internal jargon");
assert.ok(appJs.includes("MediaRecorder"), "voice recording should store audio with MediaRecorder");
assert.ok(appJs.includes("audioClips"), "audio clips should be kept in client state");
assert.ok(appJs.includes("/api/parse-material"), "uploads should call material parsing API");
assert.ok(appJs.includes("正在拆解实验方案"), "intake should show a specific loading state while the LLM breaks down the experiment");
assert.ok(appJs.includes("loginWithDemo"), "demo login should be wired");
assert.ok(appJs.includes("inviteMember"), "workspace invite action should be wired");
assert.ok(appJs.includes("postDiscussion"), "workspace discussion action should be wired");
assert.ok(appJs.includes("SESSION_STORAGE_KEY"), "workspace demo state should persist locally");
assert.ok(appJs.includes("hydrateSession"), "workspace should reload prior discussion state");
assert.ok(appJs.includes("persistSession"), "workspace changes should be saved");
assert.ok(appJs.includes("defaultStepForMode"), "mode should choose the initial workflow step");
assert.ok(appJs.includes("setMode"), "mode switching should be wired");
assert.ok(appJs.includes("openOverview"), "global overview should open without changing workflow steps");
assert.ok(indexHtml.includes("data-task-grid"), "global overview progress container should be present");
assert.ok(appJs.includes("padStart(2"), "global overview should keep numbered status blocks");
assert.ok(appJs.includes("结果报告"), "global overview should include all 8 workflow states");
assert.ok(appJs.includes("已确认"), "completed overview states should be green confirmed states");
assert.ok(appJs.includes("需要确认"), "global overview should explain what the user needs to confirm");
assert.ok(appJs.includes("完成标准"), "global overview should explain the completion criteria");
assert.equal(appJs.includes("renderModelRouter"), false, "copilot model router should be rolled back");
assert.equal(appJs.includes("renderSourceReview"), false, "copilot source evidence should be rolled back");
assert.equal(appJs.includes("renderSamplingNote"), false, "copilot sampling total should be rolled back");
assert.ok(appJs.includes("hypothesisDraft"), "copilot hypothesis draft renderer should be restored");
assert.ok(appJs.includes("syncCopilotEdits"), "copilot fields should be editable before compile");

const publicContent = `${indexHtml}\n${appJs}`;

assert.equal(/收益框架|损失框架|风险偏好|risk-seeking|riskSeeking/.test(publicContent), false);
