import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const indexHtml = await readFile(new URL("../public/index.html", import.meta.url), "utf-8");
const appJs = await readFile(new URL("../public/app.js", import.meta.url), "utf-8");
const pipelineJs = await readFile(new URL("../lib/pipeline.mjs", import.meta.url), "utf-8");
const principlesGuide = await readFile(new URL("../prompts/experiment_design_principles.md", import.meta.url), "utf-8");

const textareaMatch = indexHtml.match(/<textarea[\s\S]*?data-input-content[\s\S]*?>([\s\S]*?)<\/textarea>/);
const rowsMatch = indexHtml.match(/<textarea[\s\S]*?data-input-content[\s\S]*?rows="(\d+)"/);

assert.ok(textareaMatch, "intake textarea should exist");
assert.equal(textareaMatch[1].trim(), "", "intake textarea should start empty");
assert.ok(rowsMatch, "intake textarea should define a compact row count");
assert.equal(Number(rowsMatch[1]) <= 7, true, "intake textarea should not dominate the landing page");
assert.ok(indexHtml.includes("按住录音"), "voice input should be press-and-hold recording");
assert.ok(indexHtml.includes("松开保存音频"), "voice input should store audio rather than claim transcription");
assert.ok(indexHtml.includes("上传并解析材料"), "upload materials entry should expose parsing");
assert.ok(indexHtml.includes("交给我们"), "submit should hand off to the system");
assert.equal(indexHtml.includes("自动转写"), false, "voice UI should not promise transcription yet");
assert.ok(indexHtml.includes("data-page=\"landing\""), "landing page should exist");
assert.ok(indexHtml.includes("data-page=\"auth\""), "login/register page should exist");
assert.ok(indexHtml.includes("从好奇心到快速可上手的 LLM 行为实验"), "landing headline should reflect the new positioning");
assert.equal(indexHtml.includes("从小组讨论到可运行的 LLM 行为实验"), false, "old landing headline should be removed");
assert.ok(indexHtml.includes("abstract-map"), "landing should use an abstract process visual");
assert.equal(indexHtml.includes("实验控制台"), false, "landing visual should not look like a console screenshot");
assert.equal(indexHtml.includes("class=\"mode-choice\""), false, "auth page should not ask users to choose personal/team mode");
assert.equal(indexHtml.includes("demo@llm-lab.local"), false, "auth and landing should not expose demo account details");
assert.ok(indexHtml.includes("stage-workspace"), "team workspace should exist");
assert.ok(indexHtml.includes("个人模式"), "personal workflow mode should be available");
assert.ok(indexHtml.includes("团队模式"), "team workflow mode should be available");
assert.ok(indexHtml.includes("data-mode-option=\"personal\""), "personal mode option should be wired");
assert.ok(indexHtml.includes("data-mode-option=\"team\""), "team mode option should be wired");
assert.ok(indexHtml.includes("data-team-only=\"true\""), "workspace step should be team-only");
assert.ok(indexHtml.includes("<span>01</span> 需求输入"), "workflow step 01 should be localized");
assert.ok(indexHtml.includes("<span>02</span> 细节确认"), "workflow step 02 should be detail confirmation");
assert.equal(indexHtml.includes("<span>02</span> 需求确认"), false, "workflow step 02 should not use the old demand confirmation label");
assert.ok(indexHtml.includes("<span>03</span> 实验协议"), "workflow step 03 should be protocol review");
assert.ok(indexHtml.includes("protocol-actions"), "protocol next-step button should live below the review content");
const protocolSectionHead = indexHtml.match(/<section class="stage" id="stage-protocol">[\s\S]*?<div class="two-col">/)?.[0] || "";
assert.equal(protocolSectionHead.includes('data-action="confirm-protocol"'), false, "protocol next-step button should not sit in the top header");
assert.ok(indexHtml.includes("<span>08</span> 结果报告"), "workflow step 08 should be localized");
assert.equal(indexHtml.includes("data-step-target=\"breakdown\""), false, "overview should not be a linear workflow step");
assert.ok(indexHtml.includes("global-overview"), "global overview card should live outside the workflow steps");
assert.ok(indexHtml.includes("确认并生成实验协议"), "copilot should send the user directly to protocol generation");
assert.ok(appJs.includes('setStep("protocol")'), "copilot compile should continue to protocol, not overview");
assert.equal(appJs.includes('setStep("breakdown")'), false, "overview should not be a blocking workflow destination");
assert.equal(indexHtml.includes("Research Intake"), false, "visible page title should not fall back to English");
assert.equal(indexHtml.includes("Task Breakdown"), false, "task breakdown label should not fall back to English");
assert.ok(indexHtml.includes("全局状态总览"), "global status overview copy should render");
assert.equal(indexHtml.includes("Report preview"), false, "report preview label should be localized");
assert.ok(indexHtml.includes("邀请成员"), "workspace should support inviting members");
assert.ok(indexHtml.includes("团队讨论"), "workspace should expose shared discussion");
assert.ok(indexHtml.includes("data-hypothesis-draft"), "previous copilot hypothesis draft field should be restored");
assert.equal(indexHtml.includes("data-human-baseline"), false, "human baseline decision should be deferred to phase two");
assert.equal(indexHtml.includes("需要人类基线导出材料"), false, "human baseline option should not appear in copilot");
assert.equal(indexHtml.includes("导出人类基线"), false, "human baseline export should not appear in the results step");
assert.equal(indexHtml.includes("data-action=\"export-human\""), false, "human baseline export action should be removed from the visible UI");
assert.equal(indexHtml.includes("<h3>尚未确认</h3>"), false, "copilot should not show a separate unconfirmed section");
assert.equal(indexHtml.includes("确认我是否理解对了"), false, "detail confirmation should not repeat an explanatory section title");
assert.equal(indexHtml.includes("panel-hint"), false, "detail confirmation should not show redundant review guidance");
assert.equal(indexHtml.includes("copilot-understanding"), false, "detail confirmation should not show a separate understanding preface");
assert.ok(indexHtml.includes("<span>研究目标摘要</span>"), "detail confirmation should start with the editable study summary");
assert.ok(indexHtml.includes("data-benchmark-input"), "benchmark outcome should allow a benchmark name or link");
assert.ok(indexHtml.includes("<select data-models-input>"), "model list should be selected from a dropdown in model budget");
assert.equal(indexHtml.includes("inline-run-details"), false, "detail confirmation should not duplicate model or repetition settings");
assert.equal(indexHtml.includes("data-reps-input"), false, "detail confirmation should not include repetition controls");
assert.equal((indexHtml.match(/data-models-input/g) || []).length, 1, "model dropdown should only render once in model budget");
assert.equal(indexHtml.includes("<h3>研究细节确认</h3>"), false, "detail confirmation should not add a redundant panel heading");
assert.equal(indexHtml.includes("<h3>运行前要确定的细节</h3>"), false, "detail confirmation should not start with run settings");
assert.equal(indexHtml.includes("<h3>Copilot 摘要</h3>"), false, "copilot summary should not be the primary panel heading");
assert.equal(indexHtml.includes("Behavior prompts"), false, "copilot should not expose heavy behavior prompt checks");
assert.equal(indexHtml.includes("data-behavior-prompts"), false, "behavior prompts should stay out of the quick-pilot UI");
assert.equal(appJs.includes("behaviorPrompts"), false, "behavior prompts should not be rendered by the UI");
assert.ok(pipelineJs.includes("自由回答"), "free response measurement option should be generated");
assert.ok(pipelineJs.includes("打分 1-10"), "1-10 rating measurement option should be generated");
assert.ok(pipelineJs.includes("选择题"), "multiple-choice measurement option should be generated");
assert.ok(pipelineJs.includes("经典 benchmark 表现"), "benchmark measurement option should be generated");
assert.ok(principlesGuide.includes("operationalization"), "DOE-inspired operationalization guide should exist");
assert.ok(principlesGuide.includes("planned_comparisons"), "DOE-inspired planned comparison guide should exist");
assert.ok(pipelineJs.includes("内部实验设计原则"), "pipeline should inject the principle guide into the system prompt");
assert.equal(indexHtml.includes("deepseek + minimax 2.7"), false, "model dropdown should not include a mixed-model option");
assert.ok(indexHtml.includes("<option value=\"deepseek\" selected>deepseek</option>"), "deepseek should be the default single model");
assert.ok(indexHtml.includes("<option value=\"minimax 2.7\">minimax 2.7</option>"), "minimax should be available as a single model");
assert.ok(indexHtml.includes("重复试次"), "formal repetitions should use trial-count wording");
assert.equal(indexHtml.includes("status-pills"), false, "topbar should not show low-value status pills");
assert.equal(indexHtml.includes("data-status-intake"), false, "intake status chip should be removed");
assert.equal(indexHtml.includes("data-status-run"), false, "run status chip should be removed");
assert.equal(indexHtml.includes("intake empty"), false, "status copy should avoid internal jargon");
assert.equal(indexHtml.includes("no run"), false, "status copy should avoid internal jargon");
assert.ok(appJs.includes("MediaRecorder"), "voice recording should store audio with MediaRecorder");
assert.ok(appJs.includes("audioClips"), "audio clips should be kept in client state");
assert.ok(appJs.includes("/api/parse-material"), "uploads should call material parsing API");
assert.ok(appJs.includes("loginWithDemo"), "demo login should be wired");
assert.ok(appJs.includes("inviteMember"), "workspace invite action should be wired");
assert.ok(appJs.includes("postDiscussion"), "workspace discussion action should be wired");
assert.ok(appJs.includes("SESSION_STORAGE_KEY"), "workspace demo state should persist locally");
assert.ok(appJs.includes("hydrateSession"), "workspace should reload prior discussion state");
assert.ok(appJs.includes("persistSession"), "workspace changes should be saved");
assert.ok(appJs.includes("defaultStepForMode"), "mode should choose the initial workflow step");
assert.ok(appJs.includes("setMode"), "mode switching should be wired");
assert.ok(appJs.includes("openOverview"), "global overview should open without changing workflow steps");
assert.ok(indexHtml.includes("data-task-grid"), "global overview progress container should be present");
assert.ok(appJs.includes("padStart(2"), "global overview should keep numbered status blocks");
assert.ok(appJs.includes("结果报告"), "global overview should include all 8 workflow states");
assert.ok(appJs.includes("已确认"), "completed overview states should be green confirmed states");
assert.ok(appJs.includes("需要确认"), "global overview should explain what the user needs to confirm");
assert.ok(appJs.includes("完成标准"), "global overview should explain the completion criteria");
assert.equal(appJs.includes("renderModelRouter"), false, "copilot model router should be rolled back");
assert.equal(appJs.includes("renderSourceReview"), false, "copilot source evidence should be rolled back");
assert.equal(appJs.includes("renderSamplingNote"), false, "copilot sampling total should be rolled back");
assert.ok(appJs.includes("hypothesisDraft"), "copilot hypothesis draft renderer should be restored");
assert.ok(appJs.includes("syncCopilotEdits"), "copilot fields should be editable before compile");

const publicContent = `${indexHtml}\n${appJs}`;

assert.equal(/收益框架|损失框架|风险偏好|risk-seeking|riskSeeking/.test(publicContent), false);
